# Generated by Django 5.1.7 on 2025-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_tools', '0002_encryptedmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('is_secure', models.BooleanField(default=False)),
                ('privacy_risks', models.TextField(blank=True)),
            ],
        ),
    ]
