# Generated by Django 5.1.7 on 2025-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_tools', '0003_emailcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('stripped_file', models.FileField(blank=True, null=True, upload_to='stripped/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
