# Generated by Django 5.1.7 on 2025-03-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_tools', '0004_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
