# Generated by Django 5.1.7 on 2025-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_tools', '0005_remove_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_phishing', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
