# Generated by Django 5.1.7 on 2025-03-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationmodel',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userregistrationmodel',
            old_name='loginid',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='status',
        ),
    ]
