# Generated by Django 5.1.7 on 2025-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_userregistrationmodel_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.TextField(max_length=255),
        ),
    ]
